image: registry.gitlab.com/pages/hugo/hugo_extended:latest

pages:
  script:
  - cd src
  - hugo --minify --environment gitlab
  - mv public ../
  artifacts:
    paths:
    - public
  only:
  - master
